version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.13.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.13.2
    ports:
      - 5601:5601
    depends_on:
      - "elasticsearch"
